line-length = 88
target-version = "py312"

[lint]
select = [
    "E",   # pycodestyle
    "F",   # pyflakes
    "I",   # isort
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "S",   # flake8-bandit
    "C4",  # flake8-comprehensions
    "DTZ", # flake8-datetimez
    "T20", # flake8-print
    "RET", # flake8-return
    "SIM", # flake8-simplify
    "PTH", # flake8-use-pathlib
    "ERA", # eradicate
    "PL",  # pylint
    "TRY", # tryceratops
]

[lint.per-file-ignores]
"tests/**/*.py" = [
    "S101",    # Allow assert statements in tests
    "PLR2004", # Allow magic numbers in tests
    "S105",    # Allow possible hardcoded passwords in tests
    "S106",    # Allow possible hardcoded passwords in tests
    "S107",    # Allow possible hardcoded passwords in tests
    "ARG001",  # Allow unused function arguments (for fixtures)
    "ARG002",  # Allow unused method arguments (for overrides/fixtures)
    "FBT001",  # Allow boolean positional arguments
    "FBT002",  # Allow boolean default values
    "E501",    # Line length for test data can sometimes be longer
    "PT004",   # Allow pytest fixtures without explicit return annotation
    "PT005",   # Allow pytest fixtures without docstrings
    "PT011",   # Allow pytest raises without exception match
    "PT019",   # Allow fixture with same name as test
]

[lint.isort]
known-first-party = ["axiom_mcp"]
force-single-line = true
